services:
  mysql:
    image: "docker.io/library/mysql:9.3"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "8000:3306"
    networks:
      - "aspire"
  api:
    image: "${API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8001"
      ConnectionStrings__mysqldb: "Server=mysql;Port=3306;User ID=root;Password=${MYSQL_PASSWORD};Database=mysqldb"
    ports:
      - "8002:8001"
      - "8004:8003"
    depends_on:
      mysql:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
